"""update cascade delete behavior

Revision ID: 40e773380e87
Revises: 06bd99f32d36
Create Date: 2025-05-04 15:31:10.832892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e773380e87'
down_revision: Union[str, None] = '06bd99f32d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_rooms_student_id_fkey', 'chat_rooms', type_='foreignkey')
    op.drop_constraint('chat_rooms_teacher_id_fkey', 'chat_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'chat_rooms', 'students', ['student_id'], ['sap_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_rooms', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.create_foreign_key('chat_rooms_teacher_id_fkey', 'chat_rooms', 'teachers', ['teacher_id'], ['teacher_id'])
    op.create_foreign_key('chat_rooms_student_id_fkey', 'chat_rooms', 'students', ['student_id'], ['sap_id'])
    # ### end Alembic commands ###
