"""added xyz to contact-us

Revision ID: 43067d4b78bd
Revises: 2559ed89c52b
Create Date: 2025-05-04 12:20:54.693905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43067d4b78bd'
down_revision: Union[str, None] = '2559ed89c52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('xyz', sa.String(), nullable=False , server_default='xyz'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_us', 'xyz')
    # ### end Alembic commands ###
